-- Add new pipeline statuses to VideoStatus enum
-- The order matters for visual pipeline progression; INSERT BEFORE 'READY'
-- keeps UPLOADED → EXTRACTING → TRANSCRIBING → GENERATING → READY_FOR_REVIEW visually adjacent.

ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'EXTRACTING' BEFORE 'READY';
ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'TRANSCRIBING' BEFORE 'READY';
ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'GENERATING' BEFORE 'READY';
ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'READY_FOR_REVIEW' BEFORE 'READY';
ALTER TYPE "VideoStatus" ADD VALUE IF NOT EXISTS 'FAILED' AFTER 'PUBLISH_FAILED';

-- Add new columns to the videos table
ALTER TABLE "videos" ADD COLUMN IF NOT EXISTS "s3KeyAudio" TEXT;
ALTER TABLE "videos" ADD COLUMN IF NOT EXISTS "s3KeyFramesPrefix" TEXT;
ALTER TABLE "videos" ADD COLUMN IF NOT EXISTS "frameCount" INTEGER;
ALTER TABLE "videos" ADD COLUMN IF NOT EXISTS "durationSeconds" INTEGER;
